services:
  app:
    build: .
    depends_on:
      - postgres
      - redis
    networks:
      - netapp
    ports:
      - 8888:8888
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=1
    volumes:
      - data_postgres:/var/lib/postgresql/data
    networks:
      - netapp

  redis:
    image: redis
    volumes:
      - data_redis:/data
    networks:
      - netapp

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    networks:
      - netapp
    depends_on:
      - postgres
    command:
      [
        "-path=/migrations",
        "-database=postgres://postgres:1@postgres:5432/postgres?sslmode=disable",
        "up"
      ]

volumes:
  data_postgres: {}
  data_redis: {}

networks:
  netapp: {}
