name: Deploy Backend to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/ranandasatria/fgo24-be-tickitz:latest

      - name: Copy migrations to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: 9301
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          source: "migrations"
          target: "/home/nanda/deploy"

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: 9301
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            set -e

            cd /home/nanda/deploy

            docker pull ghcr.io/ranandasatria/fgo24-be-tickitz:latest
            docker compose up -d postgres redis

            docker run --rm \
              --network deploy_netapp \
              -v "$PWD/migrations:/migrations" \
              migrate/migrate \
              -path=/migrations \
              -database "postgres://postgres:1@postgres:5432/postgres?sslmode=disable" \
              up

            docker run --rm \
              --network deploy_netapp \
              --env-file .env \
              ghcr.io/ranandasatria/fgo24-be-tickitz:latest \
              /app/seed_tmdb

            docker compose up -d --build app
